### ISSUE TITLE
Process failed to start: too many open files

### ISSUE THREAD

**Issue by nottyl** [f-person/auto-dark-mode.nvim#4] opened 2023-05-25 07:35 UTC
Hello, I was using `auto-dark-mode.nvim` and encountered this issue. Whenever I open the terminal using `toggleterm.nvim` it shows this error. 
```
stack traceback:
^I[C]: in function 'jobstart'
^I...im/lazy/auto-dark-mode.nvim/lua/auto-dark-mode/utils.lua:8: in function 'start_job'
^I...vim/lazy/auto-dark-mode.nvim/lua/auto-dark-mode/init.lua:23: in function 'callback'
^I...im/lazy/auto-dark-mode.nvim/lua/auto-dark-mode/utils.lua:48: in function 'check_is_root'
^I...vim/lazy/auto-dark-mode.nvim/lua/auto-dark-mode/init.lua:16: in function 'check_is_dark_mode'
^I...vim/lazy/auto-dark-mode.nvim/lua/auto-dark-mode/init.lua:48: in function <...vim/lazy/auto-dark-mode.nvim/lua/auto-dark-mode/init.lua:47> function: builtin#18 Vim:E903: Process failed to start: too many open files: "/usr/local/bin/fish"
```
The screenshot below is the amount of files I currently opened. Is there any reason as to why this is happening and how can I resolve this issue? 

<img width="1552" alt="neovim broken leh" src="https://github.com/f-person/auto-dark-mode.nvim/assets/71718049/a1a49718-e110-470e-aa91-555fbdb575f0">

**Comment by nottyl** [comment] 2023-05-30 08:30
Huh, seems like some people are experiencing this with other plugins?
https://github.com/folke/trouble.nvim/issues/173
https://github.com/neovim/neovim/issues/14192

My current fix is that I added `ulimit -n 2048` to my shell config, but still not sure what exactly went wrong.

**Comment by f-person** [comment] 2023-05-30 13:28
Hi, @leana8959! Thank you, that's pretty useful; I'll take a look at the job API and see if maybe I missed something ^_^

**Comment by f-person** [comment] 2023-05-30 13:55
@nottyl, could you try the `fix/jobstop` branch and see if that fixes your issue? I'm not sure it's actually going to do anything since `jobstop` seems to forcefully terminate the process (which should be closed anyways), but it could :)

**Comment by nottyl** [comment] 2023-05-31 09:16
unfortunately, no... this is an odd bug to be honest
<img width="1394" alt="Screenshot 2023-05-31 at 17 15 48" src="https://github.com/f-person/auto-dark-mode.nvim/assets/71718049/aad60ee2-a784-45d5-b1d2-96260c67b97b">

**Comment by f-person** [comment] 2023-05-31 09:36
That's unfortunate :(
As a workaround, I would suggest either disabling the plugin in toggleterm or considering using a separate top-down terminal. I use `iTerm2` triggered on command+shift+enter and `wezterm` as a "work terminal". I've been using this setup for a couple of years now, and it works perfectly for me (I prefer to always have an open terminal with preserved state, not only inside nvim)

**Comment by leana8959** [comment] 2023-06-03 13:31
@nottyl Could you provide a minimum configuration that reproduces the error?

You can use `nvim -u` to specify a `init.lua` that's separate from your current config, and set `NVIM_APPNAME` to `adm_dbg` for example (learn more `:h NVIM_APPNAME`)

Have a nice day :)

**Comment by f-person** [comment] 2023-08-02 12:32
hey @nottyl, hope you're having a lovely day! i think the latest version should resolve your issue! lmk if it works for you!

**Comment by f-person** [comment] 2023-08-05 23:55
gonna close this issue for now, i belive it should be fixed! feel free to reopen in case it's not :)

**Closed by f-person** 2023-08-05 23:55 UTC
Labels: bug, help wanted
